openapi: "3.0.0"
info:
  version: "0.0.1"
  title: "Swagger UI Webpack Setup"
  description: "Demonstrates Swagger UI with Webpack including CSS and OAuth"
servers:
  - url: "https://api.scryfall.com"
    description: "gfycat api"
components:
  securitySchemes:
    # See https://demo.identityserver.io/ for configuration details.
    identity_server_auth:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: "https://demo.identityserver.io/connect/authorize"
          scopes:
            api: "api"
security:
  - identity_server_auth:
    - api
paths:
  /cards/random:
    get:
      summary: "Returns a single random Card object"
      parameters:
        - name: q
        in: path
        required: false
        description: An optional fulltext search query to filter the pool of random cards. Make sure that your parameter is properly encoded.
        schema:
          type: String
        - name: format
        in: path
        required: false
        description: The data format to return: json, text, or image. Defaults to json.
        schema:
          type: String 
      responses:
        401:
          description: "Unauthorized"
        200:
          description: "OK"
